# Generated by Django 5.1.7 on 2025-03-28 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0002_jobapplication"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobapplication",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Approved", "Approved"),
                    ("Rejected", "Rejected"),
                ],
                default="Pending",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="cover_letter",
            field=models.TextField(blank=True, null=True),
        ),
    ]
